---
title: "Project 1"
author: "SDS348 Fall 2019"
date: "10/20/2019"
output:
  html_document: default
  pdf_document: default
---
The 2 datasets I chose were about arthritis and epilepsy. I am interested in the medical field and have personal experience with both conditions. The arthritis dataset is about those that did a blind trial to see the improvement from a new treatment for arthritis. The epilepsy dataset is similar in that it is testing a anit-epilepsy drug called Progabide, however it is not a blind trial. The patients follow a routine check up to document how many seizures they have had while either being on a placebo or the drug. 

```{R}
library(readr)
epilepsy_1_ <- read_csv("~/epilepsy (1).csv")
Arthritis <- read_csv("~/Arthritis.csv")
library(ggplot2)
library(tidyverse)
epilepsy1<-epilepsy_1_%>%select(-X1,-Base4,-Age10,-Age,-Trt)
arthritis1<-Arthritis%>%select(-X1,-Age,-Treatment)
arthritis2<-arthritis1%>%mutate(ID= ID*2)
dat<-arthritis2%>%inner_join(epilepsy1, by=c("ID"))
```
I decided to take out several columns in the epilepsy dataset including Base4 and Age10 which did not add anything to the data, it was just Base/4 and Age/10. I also decided to take out Age and Treatment group because there was an overlap with arthritis that did not match up and led to 0 observations in my data. I was more interested in the improvement and the number of epilepsy attacks. I did a inner join because I didn't want any NA's, but regardless of a full or inner join, I had the same outcome because I took out the columns that would result in a lot of NA's as they had no common variables.  I also multiplied the column ID by 2 for arthritis so that there would be ID numbers in common. It did not change the data. 


```{R}
h<-dat%>%select(Y1, Base, Ysum)
cor(h)
dat %>% filter(Sex == "Female") %>% select(Improved, Base) %>% group_by(Improved)%>% summarize(mean = mean(Base),sd = sd(Base), count = n()) %>% mutate(se = sd/sqrt(count))

dat%>%arrange(ID)

dat %>%group_by(Improved) %>%
  summarise(mean = mean(Ysum), n = n())

dat %>%group_by(Sex) %>%
  summarise(mean = mean(Ysum), n = n())

dat %>%
  summarise(mean = mean(Y1), n = n())
dat %>%
  summarise(mean = mean(Y2), n = n())

dat %>%
  summarise(mean = mean(Y3), n = n())

dat %>%
  summarise(mean = mean(Y4), n = n())

dat %>%
  summarise(mean = mean(Base), n = n())
dat %>%
  summarise(mean = mean(Ysum), n = n())

```    
I also wanted to see if there was a correlation between before and after treatment for epileptic attacks, so I looked at the number of epileptic attacks prior to the 8 week testing period, number of epileptic attacks up till the first follow up and the total number of epileptic attacks after all the follow ups. The result was that if you had a lot of attacks after starting the treatment, up till the first follow up and after the 4 follow ups, you would have a similar amount of attacks. I think this could be because you have already started taking the drug and thus the amount of help it can give a patient is seen in the first follow up and won't be a drastic change at the end of treatment. 
For summary statistics, I filtered the data for just females as they were the majority. I found the mean, standard deviation, count and standard error for the number of seizures before treament started in the Improved column. The result was that before treatment, those that did not have improvements from treatment had the least amount of seizures, those that had some improvement had the highest amount of seizures in the beginning and those that had improvement had a median between those two groups. The data had the biggest group in those that saw improvements. Those that saw some improvement had the smallest standard error which indicates a small spread between the distribution in the sample. 
I found all the means of the epilepitc seizures after each follow up and before and after treatment. The highest mean was from Ysum which makes sense as over an 8 week period, the number of seizures would accumulate. 
I also grouped by sex and improved to see the mean of seizures after the treatment for each group. The result for improved was that those that had an improvement had the smallest mean and those that had no improvement ahd the largest mean which is logical as an improvement in seizures should correspond with a lower number of seizures.  The result of Sex is that females had a smaller mean, however this does not show as much of a relationship as Improved did because they had different counts. 

```{R}
p<-dat%>%select_if(is.numeric)%>%scale
f<-prcomp(p)
eigval<-f$sdev^2 
varprop=round(eigval/sum(eigval),2)
f$rotation
ggplot()+geom_bar(aes(y=varprop,x=1:7),stat="identity")+xlab("")+geom_path(aes(y=varprop,x=1:7))+
 geom_text(aes(x=1:7,y=varprop,label=round(varprop,2)),vjust=1,col="white",size=5)+
 scale_y_continuous(breaks=seq(0,.6,.2),labels = scales::percent)+
 scale_x_continuous(breaks=1:10)
```    
From the plot, I found that 69% of the variance is measure by PC1 and 14% is measure by PC2. These are the 2 main Principal Components I will focus on as it makes up >80% of the variance. 
In PC1, Y1, Y2, Y3, Y4, Base and Ysum are all correlated to each other as they have similar numbers. Therefore, the number of seizures before and after treatment are related. The higher the seizures they have in the beginning, the more seizures they have in the end in relation to other participants. PC2, showcase the same argument as almost all of Y1, Y2, Y3, Y4, Base and Ysum are in the negative direction or very small showcasing all of the variables are related. The only unrelated variable is ID because it is an unrelated variable and has nothing to do with the number of seizures a patient would have. 
```{R}
dat%>%ggplot(aes(Base,Ysum,color=Improved),stat="summary")+geom_point()+ggtitle("Improvement Before and After Trials")+theme_dark()
dat%>%ggplot(aes(Ysum,Improved,color=Sex))+geom_point()+ggtitle("After Treatment Improvement by Gender")+scale_x_continuous(seq(from=0, to=100, by=20),name="Ysum")+theme_light()
```


The first plot showcases the relationship between the number of seizures before and after treatment and the indication of improvement or not is marked by color. From the plot, it seems that there is a relationship of those that did not have an improvement and having more seizures after the trial. This makes sense because if they did not improve, that would indicate more seizures. There also seems to be a relationship between the starting number of seizures and the ending, they don't seem drastically different which also makes sense because even with a drug treatment, it is unlikely that having 60 seizures in a 8 week period would dim down to 20 seizures in 8 weeks. 


The second plot showcases the improvement after the treatment took place centered on the sex of the individual. It seems as though males are less likely to improve than females which could arise from the fact that males are more skeptical of impvoement and tend to not pay as much attention as females do when it comes to health. However, in the data set it does not indicate whether or not improvement is measured by the doctors or individuals. 


